---
- name: Deploy user john and SSH keys to all servers
  hosts: all
  become: yes
  vars:
    target_user: john
    target_uid: 1010
    target_group: john
    target_gid: 1010
    ssh_key_type: rsa
    ssh_key_size: 4096
    authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDE... john@workstation"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDL... john@laptop"

  tasks:
    - name: Check if target group exists
      group:
        name: "{{ target_group }}"
        gid: "{{ target_gid }}"
        state: present
      tags: user_setup

    - name: Check if target user exists
      user:
        name: "{{ target_user }}"
        uid: "{{ target_uid }}"
        group: "{{ target_group }}"
        shell: /bin/bash
        home: "/home/{{ target_user }}"
        create_home: yes
        state: present
      tags: user_setup

    - name: Create .ssh directory for john
      file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"
        mode: '0700'
      tags: ssh_setup

    - name: Deploy authorized keys for john
      copy:
        content: "{{ item }}"
        dest: "/home/{{ target_user }}/.ssh/authorized_keys"
        owner: "{{ target_user }}"
        group: "{{ target_group }}"
        mode: '0600'
      loop: "{{ authorized_keys }}"
      tags: ssh_setup

    - name: Ensure sudo access for john (optional)
      lineinfile:
        path: /etc/sudoers
        line: "{{ target_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
        state: present
      when: false  # Set to true if you want to grant sudo access
      tags: sudo_setup

    - name: Verify SSH directory permissions
      file:
        path: "/home/{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"
        mode: '0700'
        recurse: yes
      tags: verification

    - name: Test SSH key authentication (optional)
      command: whoami
      become_user: "{{ target_user }}"
      register: test_result
      changed_when: false
      tags: verification