---
- name: Deploy user elvis and enable password authentication on dev hosts
  hosts: dev
  become: yes
  vars:
    # User configuration
    username: elvis
    user_comment: "Elvis User"
    user_groups: "sudo"
    user_shell: "/bin/bash"
    
    # SSH configuration
    ssh_password_auth: yes
    ssh_permit_root_login: no
    
  tasks:
    - name: Create user elvis
      user:
        name: "{{ username }}"
        comment: "{{ user_comment }}"
        groups: "{{ user_groups }}"
        shell: "{{ user_shell }}"
        create_home: yes
        state: present
        
    - name: Set password for user elvis (you'll be prompted)
      user:
        name: "{{ username }}"
        password: "{{ elvis_password | password_hash('sha512') }}"
      vars_prompt:
        - name: "elvis_password"
          prompt: "Enter password for user elvis"
          private: yes
          confirm: yes

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
        
    - name: Enable password authentication in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
        backup: yes
      notify: restart ssh

    - name: Disable root login via SSH (security best practice)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      notify: restart ssh

    - name: Ensure SSH service is enabled and running
      service:
        name: ssh
        state: started
        enabled: yes

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted